version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "12:00"
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "12:00"
    ignore:
      - dependency-name: "ch.qos.logback:logback-classic"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "ch.qos.logback:logback-core"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "org.junit:junit-bom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.apache.maven:apache-maven"
