version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "12:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "ch.qos.logback:logback-classic"
        update-types: ["version-update:semver-major"]
      - dependency-name: "ch.qos.logback:logback-core"
        update-types: [ "version-update:semver-major" ]