name: Build
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
          server-id: OSSRH
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Install gpg
        run: |
          sudo apt update && sudo apt install -y gnupg2
          export GPG_TTY=$(tty)
          echo "${{ secrets.GPG_PRI }}" | gpg --batch --import
      - name: Testing && Publishing SNAPSHOT
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          CUSTOMER_RUSER_API_URL: ${{ secrets.CUSTOMER_API_URL }}
        run: |
          ./mvnw clean --batch-mode deploy -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
      
    