name: Release Tag

on: [workflow_dispatch]

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Set up Java
      	uses: actions/setup-java@v3
		with:
          java-version: '8'
		  distribution: 'temurin'
		  cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Perpare
        run: |
          sudo apt update && sudo apt install -y bc
      - uses: fregante/setup-git-user@v2
      - name: Tag
        run: |
           ./ci/script/commit-next-version.sh